{
    "name": "Hajjaj.Pro Accounting Financial Reports",
    "version": "18.0.1.3",
    "category": "Invoicing Management",
    "description": "Hajjaj.Pro Accounting Financial Reports",
    "summary": "Hajjaj.Pro Accounting Financial Reports",
    "sequence": "1",
    "author": "Hajjaj.Pro, MTJR.Cloud",
    "license": "LGPL-3",
    "company": "Hajjaj.Pro",
    "maintainer": "Hajjaj.Pro",
    "website": "https://hajjaj.pro",
    "support": "odooapps@hajjaj.pro",
    "depends": ["account", "report_xlsx"],
    "data": [
        "security/ir.model.access.csv",
        "data/account_account_type.xml",
        "views/menu.xml",
        "views/ledger_menu.xml",
        "views/financial_report.xml",
        "views/settings.xml",
        "wizard/account_report_common_view.xml",
        "wizard/partner_ledger.xml",
        "wizard/general_ledger.xml",
        "wizard/trial_balance.xml",
        "wizard/balance_sheet.xml",
        "wizard/profit_and_loss.xml",
        "wizard/tax_report.xml",
        "wizard/aged_partner.xml",
        "wizard/journal_audit.xml",
        "report/report.xml",
        "report/report_partner_ledger.xml",
        "report/report_general_ledger.xml",
        "report/report_trial_balance.xml",
        "report/report_financial.xml",
        "report/report_tax.xml",
        "report/report_aged_partner.xml",
        "report/report_journal_audit.xml",
        "report/report_journal_entries.xml",
        "views/optimization_tools.xml",
    ],
    "external_dependencies": {
        "python": ["psutil", "xlsxwriter"],
    },
    "pre_init_hook": "_pre_init_clean_m2m_models",
    "post_init_hook": "_post_init_hook",
}
